Alternate fix for the SSL Issue
tardis-sn/carsus pull request #331
Opened 2023-03-16 15:14 UTC by atharva-2001

### :pencil: Description

**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`

Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.

Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2023-03-18 15:51 UTC, s-rathi requested changes

2023-03-18 15:51 UTC, s-rathi commented on carsus/io/util.py
> +    retries=10,
As I mentioned in #330, hardcoding the retries to 10 may not be the best way to handle the issue.

2023-03-27 10:33 UTC, chvogl approved these changes
This looks good! I only noticed two small issues in one of the docstrings. We should decide soon which one of the two possible solutions we are going to merge @atharva-2001 @epassaro.

2023-03-27 10:33 UTC, chvogl commented on carsus/io/util.py
> +    retries : int, default: 5, optional
```suggestion
    n_retry : int, default: 15, optional
```

2023-03-27 10:33 UTC, chvogl commented on carsus/io/util.py
> +    response: requests.Response
```suggestion
    response : requests.Response
```

2023-03-30 15:55 UTC, merged